# Generated by Django 4.2 on 2026-02-14 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='desc',
            field=models.CharField(default='None', max_length=300),
            preserve_default=False,
        ),
    ]
