# Generated by Django 4.2 on 2026-02-16 09:56

import Blogs.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('author', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=Blogs.models.Blog.blog_cover_upload_path)),
            ],
        ),
    ]
