# Generated by Django 4.2 on 2026-01-09 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_membership_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='request_message',
            field=models.TextField(blank=True, help_text='Message when requesting to join'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Request'), ('accepted', 'Accepted Member'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
