# Generated by Django 4.2 on 2026-01-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='require_email_verification',
            field=models.BooleanField(default=True, help_text='Require users to verify their email before logging in'),
        ),
    ]
