# Generated by Django 4.2 on 2026-01-09 05:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('events_ctf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(db_index=True, help_text='Submitted flag', max_length=500)),
                ('status', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid')], default='incorrect', max_length=20)),
                ('points_awarded', models.PositiveIntegerField(default=0, help_text='Points awarded for this submission')),
                ('points_at_submission', models.PositiveIntegerField(default=0, help_text='Challenge points at time of submission')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of submission', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent of submission', max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this submission')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.challenge')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='events_ctf.event')),
                ('instance', models.ForeignKey(blank=True, help_text='Instance this submission is for (if instance-based challenge)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='challenges.challengeinstance')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('copied_flag', 'Copied Flag'), ('shared_flag', 'Shared Flag'), ('multiple_submissions', 'Multiple Submissions'), ('rate_limit', 'Rate Limit Exceeded'), ('instance_tampering', 'Instance Tampering'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the violation')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Evidence data (flags, IPs, etc.)')),
                ('action_taken', models.CharField(blank=True, help_text="Action taken (e.g., 'Team banned', 'Points reduced')", max_length=200)),
                ('is_resolved', models.BooleanField(default=False, help_text='Violation has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('detected_by', models.CharField(default='system', help_text='Who detected the violation (system, admin username, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='challenges.challenge')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='events_ctf.event')),
                ('instance', models.ForeignKey(blank=True, help_text='Instance involved in violation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='challenges.challengeinstance')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_violations', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, help_text='Submission that triggered this violation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='submissions.submission')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='accounts.team')),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
                'db_table': 'violations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Points change (positive for awards, negative for reductions)')),
                ('score_type', models.CharField(choices=[('award', 'Points Awarded'), ('reduction', 'Points Reduced'), ('adjustment', 'Manual Adjustment')], default='award', max_length=20)),
                ('total_score', models.PositiveIntegerField(default=0, help_text='Total score after this change (cannot be negative)', validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(blank=True, help_text='Reason for score change', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='challenges.challenge')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this score entry (admin for manual adjustments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_entries', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='events_ctf.event')),
                ('submission', models.ForeignKey(blank=True, help_text='Submission that triggered this score entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_entries', to='submissions.submission')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='accounts.team')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'db_table': 'scores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['team', 'event'], name='violations_team_id_360b73_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['violation_type', 'severity'], name='violations_violati_e0eedb_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['is_resolved', 'created_at'], name='violations_is_reso_131eef_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['event', 'created_at'], name='violations_event_i_22d13b_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['team', 'challenge', 'status'], name='submissions_team_id_405624_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['event', 'submitted_at'], name='submissions_event_i_7eb0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['flag'], name='submissions_flag_83c6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'submitted_at'], name='submissions_status_ac0821_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['team', 'event'], name='scores_team_id_f00e73_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['challenge', 'event'], name='scores_challen_d3f66b_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['event', 'created_at'], name='scores_event_i_55bbb8_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['score_type'], name='scores_score_t_2c9a1d_idx'),
        ),
    ]
