# Generated by Django 4.2 on 2026-01-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='flag_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash of submitted flag for fast copy detection', max_length=128),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['flag_hash'], name='submissions_flag_ha_aa1df3_idx'),
        ),
    ]
