# Generated by Django 4.2 on 2026-02-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0002_remove_content_and_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='summary',
            field=models.TextField(help_text='Write in Markdown. Rendered as Markdown on the website.'),
        ),
    ]
