# Generated by Django 4.2 on 2026-01-09 05:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('color', models.CharField(default='#E50914', help_text='Hex color code', max_length=7)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('is_visible', models.BooleanField(default=False, help_text='Challenge is visible to participants')),
                ('is_active', models.BooleanField(default=True, help_text='Challenge is active')),
                ('points', models.PositiveIntegerField(default=100, help_text='Initial points for the challenge', validators=[django.core.validators.MinValueValidator(1)])),
                ('minimum_points', models.PositiveIntegerField(default=10, help_text='Minimum points (for dynamic scoring)', validators=[django.core.validators.MinValueValidator(1)])),
                ('decay', models.PositiveIntegerField(default=0, help_text='Points decay per solve (for dynamic scoring)')),
                ('challenge_type', models.CharField(choices=[('standard', 'Standard'), ('instance', 'Instance-based')], default='standard', help_text='Challenge type', max_length=20)),
                ('flag', models.CharField(blank=True, help_text='Flag for standard challenges', max_length=500)),
                ('flag_type', models.CharField(choices=[('static', 'Static Flag'), ('regex', 'Regex Pattern')], default='static', help_text='Flag matching type', max_length=20)),
                ('instance_config', models.JSONField(blank=True, default=dict, help_text='Docker/instance configuration (image, ports, env vars, etc.)')),
                ('instance_flag_format', models.CharField(blank=True, default='CTF{random}', help_text='Flag format template for instances (use {random} for random string)', max_length=200)),
                ('instance_time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Time limit for instances in minutes (overrides event default if set)', null=True)),
                ('release_time', models.DateTimeField(blank=True, help_text='When challenge becomes visible', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solve_count', models.PositiveIntegerField(default=0, help_text='Number of successful solves')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'db_table': 'challenges',
                'ordering': ['category', 'points', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='challenges/files/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Challenge File',
                'verbose_name_plural': 'Challenge Files',
                'db_table': 'challenge_files',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('cost', models.PositiveIntegerField(default=0, help_text='Points cost to unlock hint')),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='challenges.challenge')),
            ],
            options={
                'verbose_name': 'Hint',
                'verbose_name_plural': 'Hints',
                'db_table': 'hints',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(blank=True, db_index=True, help_text='Docker container ID', max_length=200)),
                ('instance_id', models.CharField(db_index=True, help_text='Unique instance identifier', max_length=100, unique=True)),
                ('flag', models.CharField(db_index=True, help_text='Unique flag for this instance', max_length=500)),
                ('access_url', models.URLField(blank=True, help_text='URL to access the instance')),
                ('access_port', models.PositiveIntegerField(blank=True, help_text='Port to access the instance', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('starting', 'Starting'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if instance failed')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Instance expiration time', null=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of instance config')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='challenges.challenge')),
            ],
            options={
                'verbose_name': 'Challenge Instance',
                'verbose_name_plural': 'Challenge Instances',
                'db_table': 'challenge_instances',
                'ordering': ['-started_at'],
            },
        ),
    ]
