# Generated by Django 4.2 on 2026-01-09 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('events_ctf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeinstance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='events_ctf.event'),
        ),
        migrations.AddField(
            model_name='challengeinstance',
            name='started_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengeinstance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='accounts.team'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='challenges.category'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='events_ctf.event'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='challenges', to='challenges.challengefile'),
        ),
        migrations.AddIndex(
            model_name='challengeinstance',
            index=models.Index(fields=['team', 'challenge', 'status'], name='challenge_i_team_id_29cc14_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeinstance',
            index=models.Index(fields=['container_id'], name='challenge_i_contain_60c4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeinstance',
            index=models.Index(fields=['instance_id'], name='challenge_i_instanc_d9063b_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeinstance',
            index=models.Index(fields=['flag'], name='challenge_i_flag_d670f0_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeinstance',
            index=models.Index(fields=['status', 'expires_at'], name='challenge_i_status_3f42f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeinstance',
            unique_together={('challenge', 'team', 'instance_id')},
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['event', 'is_visible', 'is_active'], name='challenges_event_i_a8edbd_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['category'], name='challenges_categor_b78b85_idx'),
        ),
    ]
