# Generated by Django 4.2 on 2026-01-09 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='max_instances_per_team',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of concurrent instances per team for this challenge', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
