# Generated by Django 4.2 on 2026-01-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events_ctf', '0001_initial'),
        ('challenges', '0003_challenge_max_instances_per_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='HintUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('cost_paid', models.PositiveIntegerField(help_text='Points deducted when unlocked')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_unlocks', to='events_ctf.event')),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='challenges.hint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_hints', to='accounts.team')),
            ],
            options={
                'verbose_name': 'Hint Unlock',
                'verbose_name_plural': 'Hint Unlocks',
                'db_table': 'hint_unlocks',
                'ordering': ['-unlocked_at'],
                'unique_together': {('hint', 'team', 'event')},
            },
        ),
    ]
