# Generated by Django 4.2 on 2026-01-09 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0004_hintunlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='allow_instance_renewal',
            field=models.BooleanField(default=False, help_text='Allow teams to renew/extend instances before expiration'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='instance_renewal_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of renewals per instance (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='instance_renewal_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Additional minutes added per renewal'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reduce_points_on_expiry',
            field=models.BooleanField(default=True, help_text='Reduce team points when instance expires'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reduce_points_on_stop',
            field=models.BooleanField(default=True, help_text='Reduce team points when user manually stops instance'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reduce_points_on_wrong_flag',
            field=models.BooleanField(default=True, help_text='Reduce team points when wrong flag submitted (additional to generic penalty)'),
        ),
        migrations.AddField(
            model_name='challengeinstance',
            name='last_renewed_at',
            field=models.DateTimeField(blank=True, help_text='When instance was last renewed', null=True),
        ),
        migrations.AddField(
            model_name='challengeinstance',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times instance has been renewed'),
        ),
        migrations.AddField(
            model_name='challengeinstance',
            name='renewed_by',
            field=models.ForeignKey(blank=True, help_text='User who last renewed instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
