# Generated by Django 4.2 on 2026-01-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_allow_instance_renewal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='instance_renewal_min_threshold',
            field=models.PositiveIntegerField(default=30, help_text='Show renew button only when instance has less than this many minutes remaining'),
        ),
    ]
