# Generated by Django 4.2 on 2026-01-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_challengeinstance_container_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeinstance',
            name='flag_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash of the instance flag for fast copy detection', max_length=128),
        ),
        migrations.AddIndex(
            model_name='challengeinstance',
            index=models.Index(fields=['flag_hash'], name='challenge_i_flag_ha_475371_idx'),
        ),
    ]
