# Generated by Django 4.2 on 2026-01-21 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_challengeinstance_flag_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='penalty_fixed_points',
            field=models.PositiveIntegerField(default=10, help_text='Fixed points to deduct per penalty', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='challenge',
            name='penalty_percentage',
            field=models.PositiveIntegerField(default=10, help_text='Percentage of challenge points to deduct (1-100%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='challenge',
            name='penalty_type',
            field=models.CharField(choices=[('percentage', 'Percentage of Challenge Points'), ('fixed', 'Fixed Points')], default='percentage', help_text='Type of penalty calculation', max_length=20),
        ),
    ]
