# Generated by Django 4.2 on 2026-01-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_challenge_penalty_fixed_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeinstance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
