# Generated by Django 4.2 on 2026-01-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_alter_challengeinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='instance_url_type',
            field=models.CharField(choices=[('web_url', 'Web URL (http://domain:port)'), ('netcat', 'Netcat (nc ip port)')], default='web_url', help_text='How to display access URL for instance (web browser or netcat)', max_length=20),
        ),
    ]
