# Generated by Django 4.2 on 2026-01-09 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        ('accounts', '0001_initial'),
        ('challenges', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_ctf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system_wide', models.BooleanField(default=False, help_text='Notification visible to all users')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('event', 'Event'), ('challenge', 'Challenge'), ('submission', 'Submission'), ('violation', 'Violation'), ('team', 'Team'), ('admin', 'Admin')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate to when notification is clicked')),
                ('action_text', models.CharField(blank=True, help_text='Text for action button', max_length=100)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification expiration time', null=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='challenges.challenge')),
                ('created_by', models.ForeignKey(blank=True, help_text='User/system that created this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events_ctf.event')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='submissions.submission')),
                ('team', models.ForeignKey(blank=True, help_text='Team recipient (null for individual user)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.team')),
                ('user', models.ForeignKey(blank=True, help_text='Specific user recipient (null for system-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='submissions.violation')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_5cf777_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['team', 'is_read', 'created_at'], name='notificatio_team_id_22908e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_system_wide', 'is_read', 'created_at'], name='notificatio_is_syst_e5a265_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'priority'], name='notificatio_notific_5536b0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event', 'created_at'], name='notificatio_event_i_b6e73c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_66996e_idx'),
        ),
    ]
