# Generated by Django 4.2 on 2026-01-10 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dismissed_by_users',
            field=models.ManyToManyField(blank=True, help_text='Users who have dismissed/cleared this notification', related_name='dismissed_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
