# Generated by Django 4.2 on 2026-01-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_dismissed_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('event', 'Event'), ('challenge', 'Challenge'), ('submission', 'Submission'), ('violation', 'Violation'), ('team', 'Team'), ('admin', 'Admin'), ('user_banned', 'User Banned')], default='system', max_length=20),
        ),
    ]
