# Generated by Django 4.2 on 2026-01-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sound_played',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether notification sound has been played (prevents replay on reload)'),
        ),
    ]
