# Generated by Django 4.2 on 2026-01-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_sound_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('event', 'Event'), ('challenge', 'Challenge'), ('challenge_release', 'Challenge Release'), ('submission', 'Submission'), ('violation', 'Violation'), ('team', 'Team'), ('admin', 'Admin'), ('user_banned', 'User Banned'), ('hint', 'Hint Release')], default='system', max_length=20),
        ),
    ]
