# Generated by Django 4.2 on 2026-01-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data for rich notifications (difficulty, points, category, cost, etc.)'),
        ),
    ]
